title: It doesn't matter Dev Blog
email: it.doesnt.matter.blog@gmail.com
author: Marek G
description: >-
  Thoughts, tools and snippets by an ex Software Engineer

github_username: itdoesnotmatter
disqus:
  shortname: itdoesnotmatter

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itdoesnotmatter.github.io/"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true
permalink: pretty

header_pages:
  - about.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
